version: '3.8'

services:
  backup-system:
    build:
      context: .
      dockerfile: docker-setup/Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    environment:
      - BACKUP_FREQUENCY=daily
    restart: always

